### ISSUE TITLE
Updating ports

### ISSUE THREAD

**Issue by noisytoken** [judge0/judge0#205]
Hi

I am deploying the judge API on a VPS.

But on my host machine port is 80 is already occupied by Nginx, how can I access judge api from another port?

**Comment by vvalchev** [comment]
if you are using docker, you can just map it to another port. Or in the docker-compose you can change the ports section:
```
services:
  server:
    image: judge0/api:1.9.0
    env_file: judge0.conf
    # volumes:
    #   - ./judge0.conf:/judge0.conf:ro
    ports:
      - "80:3000"
    privileged: true
    <<: *default-logging
    restart: always
```

Originally the service runs on port 3000. The "ports" section actually maps the port 3000 from the docker container, to port 80 on the hosting machine. Just change 80 to some other port.
