### ISSUE TITLE
Issue with deploying custom image

### ISSUE THREAD

**Issue by Datum-Guy** [judge0/judge0#250]
@hermanzdosilovic I have been trying to deploy custom image of the Judge0 system on GCP instance. I am doing this as I am in particular need of specific python and R packages. I've been following the instructions given by you in issue #232 

However, once I complete all the steps successfully and the containers are deployed. The http://<IP-ADDRESS-OF-MY-INSTANCE> is not showing any output (documentation of judge0). It's showing this error -  [https://ibb.co/xfNQf26](https://ibb.co/xfNQf26). 

Upon further investigation, I found out, that for my deployment of your default distribution (without any edits to Dockerfile) from the judge0-v1.12.0.zip, which by the way is running smoothly without any issues, the server_container has the command - `./docker-entrypoint.sh ./scripts/server`, whereas for deployment of my custom build the server_container has the command - `./docker-entrypoint.sh sleep infinity`. Here's the screenshots for the deployed containers for both the deployed versions [judge0-v1.12.0(No edits)](https://ibb.co/1zQYbrW) & [CustomBuild](https://ibb.co/QD0yRfx) . I think that might be the reason, however I am not clear how can I fix that. 

Both the deployments are on different machines, so no conflicts of any kind are possible.

I would really appreciate your help on this. :) 

## Here are all the steps I've followed, for the deployment of the custom build.

1. Cloned Judge0 repo (for step 3, 4 and 5 in issue #232 ).
2. Cloned Compilers repo (for step 1 and 2 in issue #232 ).
3. Installed Docker.io and Docker-Compose
4. (Step 1 in issue #232 ) I create a separate folder and copy Dockerfile and docker-entrypoint.sh from compilers repo to this location. Then I edit the copied Dockerfile. Here's the edited Dockerfile. No changes in docker-entrypoint.sh file.
```
FROM judge0/compilers:1.3.0-slim
# Python for ML
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install \
        mlxtend \
        numpy \
        pandas \
        requests \
        scikit-learn \
        scipy && \
    rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
```
5. Build the above Dockerfile (as mentioned in step 2 of issue #232 ) using the following command
```
sudo docker build -t judge0/basewithpythonpackages .
```
6. (Step 3 in Issue #232 ) Then I navigate to the judge0 repo and I change the image from which this Dockerfile inherits and I change it to the Image I just built. Here's the edited code for the respective Dockerfile.
```
FROM judge0/basewithpythonpackages:latest AS production

ENV JUDGE0_HOMEPAGE "https://judge0.com"
LABEL homepage=$JUDGE0_HOMEPAGE

ENV JUDGE0_SOURCE_CODE "https://github.com/judge0/judge0"
LABEL source_code=$JUDGE0_SOURCE_CODE

ENV JUDGE0_MAINTAINER "Herman Zvonimir Došilović <hermanz.dosilovic@gmail.com>"
LABEL maintainer=$JUDGE0_MAINTAINER

ENV PATH "/usr/local/ruby-2.7.0/bin:/opt/.gem/bin:$PATH"
ENV GEM_HOME "/opt/.gem/"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      cron \
      libpq-dev \
      sudo && \
    rm -rf /var/lib/apt/lists/* && \
    echo "gem: --no-document" > /root/.gemrc && \
    gem install bundler:2.1.4 && \
    npm install -g --unsafe-perm aglio@2.3.0

ENV VIRTUAL_PORT 2358
EXPOSE $VIRTUAL_PORT

WORKDIR /api

COPY Gemfile* ./
RUN RAILS_ENV=production bundle

COPY cron /etc/cron.d
RUN cat /etc/cron.d/* | crontab -

COPY . .

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["./scripts/server"]

ENV JUDGE0_VERSION "2.0.1"
LABEL version=$JUDGE0_VERSION


FROM production AS development

ARG DEV_USER=judge0
ARG DEV_USER_ID=1000

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        vim && \
    useradd -u $DEV_USER_ID -m -r $DEV_USER && \
    echo "$DEV_USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers

USER $DEV_USER

CMD ["sleep", "infinity"]
```
7. (Step 4 in Issue #232 ) Made changes to the db/languages/active.rb file and added "Python DS" as the language to the list of languages. Here's the edited portion of the code.
```
@languages ||= []
@languages +=
[
  {
    id: 43,
    name: "Plain Text",
    is_archived: false,
  ...
  ...
  ...
  {
    id: 89,
    name: "Multi-file program",
    is_archived: false,
  },
  {
    id: 90,
    name: "Python DS",
    is_archived: false,
    source_file: "script.py",
    run_cmd: "/usr/local/python-3.8.1/bin/python3 script.py"
  },
]
```
8. Build the above Dockerfile (as mentioned in step 5 of issue #232 ) using the following command
```
sudo docker build -t judge/pythonstack .
```
9. Copied docker-compose.yml and created a new compose file docker-compose.custom.yml. Made edits to this docker-compose.custom.yml file for deployment. Here's the content from docker-compose.custom.yml
```
version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: judge/pythonstack:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "80:2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge/pythonstack:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    <<: *default-logging
    restart: always

volumes:
  postgres-data:
  redis-data:
```
10. To deploy the above setup I used the following commands as mentioned in your [deployment instructions](https://github.com/judge0/judge0/blob/master/CHANGELOG.md#with-http) 
```
sudo docker-compose -f docker-compose.custom.yml up -d db redis
sleep 10s
sudo docker-compose -f docker-compose.custom.yml up -d
sleep 5s
```
