### ISSUE TITLE
Restrict judge0 from public access and allow on localhost only

### ISSUE THREAD

**Issue by armornet** [judge0/judge0#251]
Hello,
      I have installed judge0 docker image perfectly and i am able to access that on my http://myserverip:8080/  but i want that the judge0 docker container should be accessed only locally like http://localhost:8080 and public cant access it on http://myserverip:8080/

any advise will be oblidged

**Comment by batflarrow** [comment]
@armornet  Could you please explain how and where you installed the judge0 docker image for public access.

**Comment by armornet** [comment]
Actually in my server currently the judge0 is accessible on http://public-ip:8080 and my application is able to connect to it.. i wanted to know how can i change the public ip to 127.0.0.1 so that judge0 is not accessible on http://public-ip:8080 to the outside public but will be accessible for my application on http://127.0.0.1:8080..

please advise..

**Comment by hermanzdosilovic** [comment]
Hi @armornet,

I suppose that you mapped port 8080 of your host to port 3000 of Judge0 like this: `8080:3000`. Instead of that you can do the following: `127.0.0.1:8080:3000`.

**Comment by vvalchev** [comment]
I suggest that you run your own application also in the same docker-compose. Then you don't need to expose the judge0 port.

As example:
```
  server:
    image: judge0/judge0:latest-dev
    environment:
      - VIRTUAL_HOST=judge0.local
    volumes:
      - .:/api
# Do not expose ports, so Judge0 is accessible only for other containers
#    ports:
#      - "2358:2358"
#      - "3001:3001" # For ./scripts/dev/serve-docs
    privileged: true

  app:
    image: myapp:latest

```

In this case the 'app' can call judge system using `http://server:2358`. And if you want to use call-back URLs, you should pass `http://app/<path>`.

Btw you may also need to remove nginx container. It acts like a proxy for Judge0.
