### ISSUE TITLE
About Running in Privileged Mode

### ISSUE THREAD

**Issue by hamzagoc** [judge0/judge0#307]
Hi @hermanzdosilovic , I have two questions about distribution.

1- Is there a special reason to run the 'server' in privilege mode?
I ran the **'server'** in my local and AWS instance without privilege mode and I did not observe any problems.

2- It seems that **'worker'** requires being run with privilege mode because of some restrictions (one of which is 'isolate' trying to manipulate the '/sys/fs/cgroup') on accessing/manipulating host resources. How do you evaluate the possible effect of deploying with priviliged mode? As far as I know, using privilege mod is not recommended. I come up with a solution to problems by using capabilities and mounting the cgroup path as rw. I saw that you also mentioned that capabilities can be used to overcome problems. Have you ever used this approach in production? Do you see any problems / pitfalls in this configuration?

```
  server:
    image: <customimage>
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    <<: *default-logging
    restart: always
  worker:
    image: <customimage>
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cap_add:
       - CAP_SYS_ADMIN
    <<: *default-logging
    restart: always

```
