### ISSUE TITLE
Problem with setup : Postgres - could not connect to server

### ISSUE THREAD

**Issue by Aeshvarya-Mittal** [judge0/judge0#316]
`Hi` @hermanzdosilovic 
 I am getting the following error when I try to run the docker compose file on AWS EC2 instance: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432? Couldn't create 'postgres' database. Please check your configuration.rails aborted!

I am using nginx to proxy pass to different upstream servers.Snipped of docker-compose.yml for judge0 is as follows:

```
version: '2.4'
services:
  judge0-server:
    image: "judge0/judge0:1.13.0"
    hostname: "hira-web"
    volumes:
      - "${EB_LOG_BASE_DIR}/judge0-server:/var/log/sample-app"
    mem_limit: 400m
    links:
      - db
      - redis
  db:
    image: postgres:13.0
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  judge0-worker:
    image: "judge0/judge0:1.13.0"
    hostname: "hira-web"
    command: ["./scripts/workers"]
    volumes:
      - "./judge0-server:/var/service/judge0Server"
      - "${EB_LOG_BASE_DIR}/judge0-server:/var/log/sample-app"
    links:
      - db
      - redis
  redis:
      image: redis:6.0
      command: [
          "bash", "-c",
          'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
      ]
      volumes:
        - redis-data:/data
  nginx-proxy:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - "./proxy/conf.d:/etc/nginx/conf.d:ro"
      - "${EB_LOG_BASE_DIR}/nginx-proxy:/var/log/nginx"
    mem_limit: 128m
    links:
      - judge0-server

volumes:
  postgres-data:
  redis-data:
```

The conf file contains the following:

```
upstream judge0-server {
  server judge0-server:2358;
  }
stream{
    upstream db{
      server db:5432;
      }
    server {
        listen 5432 so_keepalive=on;
        proxy_pass db;
      }
  }


REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=YourPasswordHere1234


POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0

POSTGRES_PASSWORD=YourPasswordHere1234
```

The server container is exiting as it is not able to connect to db

**Comment by hermanzdosilovic** [comment]
Services judge0-worker and judge0-server do not see the `POSTGRES_HOST` environment variable.

Quick fix for this:
```
  judge0-server:
    image: "judge0/judge0:1.13.0"
    hostname: "hira-web"
    volumes:
      - "${EB_LOG_BASE_DIR}/judge0-server:/var/log/sample-app"
    mem_limit: 400m
    links:
      - db
      - redis
    environment:
        - POSTGRES_HOST=db
```

I.e. add
```
environment:
  - POSTGRES_HOST=db
```
